- name: Set SELinux mode
  ansible.posix.selinux:
    policy: targeted
    state: "{{ selinux_state }}"
  register: selinux_change

- name: Display SELinux status
  ansible.builtin.debug:
    msg: "SELinux: {{ selinux_state }}"

- name: Check SELinux mode
  ansible.builtin.command: getenforce
  register: selinux_mode
  changed_when: false