---
# Feature toggles (inherit from group_vars/login.yml when set there)
gui_enabled: false
xfce_enabled: true
x2go_enabled: true

# Performance tuning
gui_xfce_tuning_enabled: true
gui_xfce_screensaver_tuning_enabled: true
gui_xfce_power_manager_tuning_enabled: true

# Keep SSH session alive
gui_x2go_ssh_keepalive_enabled: true
gui_x2go_ssh_client_alive_interval: 60
gui_x2go_ssh_client_alive_countmax: 3

# Repositories
gui_powertools_repo: powertools

# Package lists
gui_xorg_packages:
  - xorg-x11-server-Xorg
  - xorg-x11-xauth
  - xorg-x11-server-utils
  - xorg-x11-fonts-Type1
  - xorg-x11-fonts-misc
  - xorg-x11-fonts-75dpi
  - xorg-x11-fonts-100dpi
  - dejavu-sans-fonts
  - dejavu-serif-fonts
  - liberation-fonts
  - dbus-x11

gui_xfce_packages:
  - xfce4-session
  - xfce4-panel
  - xfce4-settings
  - xfce4-terminal
  - xfce4-appfinder
  - xfdesktop
  - xfwm4
  - thunar
  - file-roller
  - firefox
  - mousepad
  - evince

gui_x2go_packages:
  - x2goserver
  - x2goserver-xsession
  - x2goserver-common

# Wallpaper - When enabled, the role will deploy a PNG (ideally with transparent background)
gui_branding_enabled: true

# Provide a role-local file.
gui_branding_logo_src: "branding/bg-logo.png"  # url under roles/login-gui/files/

# Where to install the image on the target.
gui_branding_wallpaper_path: /usr/share/backgrounds/hpc/login-logo.png

# image-style: 0=centered, 1=tiled, 3=scaled 
gui_branding_image_style: 1
